name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Swift on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift (Windows)
        if: matrix.os == 'windows-latest'
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-5.10-release
          swift-build: 5.10-RELEASE

      - name: Run tests
      - run: swift build
      - run: swift test
