name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Swift on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift (Windows)
        if: matrix.os == 'windows-2022'
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "5.9.2"

      - name: Run tests
        run: swift test
